export const requestWorks = [
  {
    id: "1",
    image: "/works/work-example.png",
    price: 120,
    serviceTitle: "House Cleaning Service",
    companyName: "Clean Co.",
    date: "01/25/25",
  },
  {
    id: "2",
    image: "/works/work-example.png",
    price: 250,
    serviceTitle: "Office Cleaning Service",
    companyName: "SparkleWorks",
    date: "02/15/25",
  },
  {
    id: "3",
    image: "/works/work-example.png",
    price: 180,
    serviceTitle: "Carpet Cleaning Service",
    companyName: "FreshStart Cleaning",
    date: "03/10/25",
  },
  {
    id: "4",
    image: "/works/work-example.png",
    price: 300,
    serviceTitle: "Deep Cleaning Service",
    companyName: "EcoClean Solutions",
    date: "04/05/25",
  },
  {
    id: "5",
    image: "/works/work-example.png",
    price: 90,
    serviceTitle: "Window Cleaning Service",
    companyName: "CrystalView Services",
    date: "05/20/25",
  },
];
